name: Build and test

on:
  push:
    branches: [ main ]
    tags-ignore:
      - '*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
        env:
          RUN_POSTINSTALL: '1'
      - run: yarn build
      - run: yarn test
